EXTRA_INCLUDEPATH += C:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/include/mariadb
QT_CPU_FEATURES.i386 = 
QT.global_private.enabled_features = sse2 alloca_malloc_h alloca avx2 dbus dbus-linked gui network relocatable sql system-zlib testlib widgets xml zstd
QT.global_private.disabled_features = alloca_h android-style-assets private_tests dlopen gc_binaries libudev posix_fallocate reduce_exports reduce_relocations release_tools stack-protector-strong
PKG_CONFIG_EXECUTABLE = pkg-config
QMAKE_LIBS_DBUS = -LC:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/lib -ldbus-1
QMAKE_INCDIR_DBUS = C:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/include/dbus-1.0 C:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/lib/dbus-1.0/include
QT_COORD_TYPE = double
QMAKE_LIBS_ZLIB = -lz
QMAKE_LIBS_ZSTD = -LC:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/lib -lzstd
CONFIG += sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples f16c force_debug_info largefile precompile_header rdrnd shani x86SimdAlways
QT_BUILD_PARTS += libs tools
QT_HOST_CFLAGS_DBUS += -IC:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/include/dbus-1.0 -IC:/Users/old_w/Documents/GitHub/ProxSpace/msys2/mingw32/lib/dbus-1.0/include
